release:
  github:
    owner: thuongnn
    name: clst-mgt-api

builds:
  - id: "api"
    main: ./cmd/server
    binary: api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

  - id: "worker"
    main: ./cmd/worker
    binary: worker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - use: docker
    goos: linux
    goarch: amd64
    skip_push: true
    dockerfile: 'Dockerfile'
    image_templates:
      - "thuongnn1997/clst-mgt-api:latest"
      - "thuongnn1997/clst-mgt-api:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=image.created={{.Date}}"
      - "--label=image.title={{.ProjectName}}"
      - "--label=image.revision={{.FullCommit}}"
      - "--label=image.version={{.Version}}"
      - "--platform=linux/amd64"

  - use: docker
    goos: linux
    goarch: amd64
    skip_push: true
    dockerfile: 'Dockerfile'
    image_templates:
      - "thuongnn1997/clst-mgt-worker:latest"
      - "thuongnn1997/clst-mgt-worker:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=image.created={{.Date}}"
      - "--label=image.title={{.ProjectName}}"
      - "--label=image.revision={{.FullCommit}}"
      - "--label=image.version={{.Version}}"
      - "--platform=linux/amd64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README.md
      - example.env
      - Makefile
    builds_info:
      group: root
      owner: root
      mode: 0644
      mtime: 2008-01-02T15:04:05Z

