version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Adm1n
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:6-alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "Adm1n123" ]
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB:
